### ISSUE TITLE
Change default start time

### ISSUE THREAD

**Issue by Li-Heng-LH** [CS2103JAN2017-F14-B1/main#42]

**Comment by fishwind** [comment]
How should we enhance? using "now" instead of "time of task added"? "now" as in the LocalDateTime for start time will not be shown. Only showing "now" word

**Comment by Li-Heng-LH** [comment]
As in, schedule  the task NOW if no time is specified is a bad idea. Suggest to schedule it one hour later. Refer to: http://www.comp.nus.edu.sg/~cs2103/AY1617S2/contents/pointsToPonderAboutProductDesign.html
